# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License.

<#
.Synopsis
    This test script runs the e2e test of aks-engine

.Description
	The script creates a environment file which is used by Linux
	test script to create resource group and deploy the cluster.
	Post the cluster deployment e2e test is executed. aks-engine
	allows to create a unmanaged kubernetes cluster with the desired
	image to be used for master and worker nodes.
#>

param([string] $TestParams, [object] $AllVmData)

function Main {
	param (
		$testParams,
		$allVMData,
		$currentTestData
    )

    # Test member variables initialization
	$testResult = "ABORTED"
	$currentTestResult = Create-TestResultObject
	$currentTestResult.TestResult = $testResult

    # Local variables
	$testName=$currentTestData.testName
    $shellScriptName="aks_engine_run_e2e_test.sh"

    # Parse test parameters
    try {
		# Extract the parameter for the e2e test
		$location = $testParams.Location
		$apiModel = $testParams.ApiModel
		$timeout = $testParams.Timeout
		$aksEngineUrl = $testParams.AKSEngineRepoUrl
		$goLangUrl = $testParams.GoLangDowloadUrl

		$fileName = "setenv"
		$workingDirectory = Get-Location
		$envFilename = Join-Path $workingDirectory $fileName

		# Fetch the Azure credentials for creating Kubernetes cluster
		$tenantID = $Global:XMLSecrets.secrets.SubscriptionServicePrincipalTenantID
		$clientID = $Global:XMLSecrets.secrets.SubscriptionServicePrincipalClientID
		$clientSecret = $Global:XMLSecrets.secrets.SubscriptionServicePrincipalKey
		$subscriptionID = $Global:XMLSecrets.secrets.SubscriptionID

		# Fetch the Azure credentials for creating Kubernetes cluster
		"export CLIENT_ID=$clientID" | Out-File $envFilename
		"export CLIENT_SECRET=$clientSecret" | Out-File $envFilename -Append
		"export SUBSCRIPTION_ID=$subscriptionID" | Out-File $envFilename -Append
		"export TENANT_ID=$tenantID" | Out-File $envFilename -Append
		"export LOCATION=$location" | Out-File $envFilename -Append
		"export CLUSTER_DEFINITION=$apiModel" | Out-File $envFilename -Append
		"export AKS_ENGINE_URL=$aksEngineUrl" | Out-File $envFilename -Append
		"export GO_LANG_DOWNLOAD_URL=$goLangUrl" | Out-File $envFilename -Append
		"export NAME=" | Out-File $envFilename -Append

		# Upload the environment files to VM
		Copy-RemoteFiles -uploadTo $allVMData.PublicIP -port $allVMData.SSHPort `
			-files $envFilename -username $user -password $password -upload | Out-Null

		# Run e2e test
		$command = "bash /home/$user/$shellScriptName 1> ${testName}_summary.log 2>&1"
		$null = Run-LinuxCmd -username $global:user -password $global:password `
			-ip $allVMData.PublicIP -port $allVMData.SSHPort -command $command `
			-ignoreLinuxExitCode -runAsSudo -runMaxAllowedTime $timeout

		$command = "cat state.txt"
		$testState = Run-LinuxCmd -username  $global:user -password  $global:password `
			-ip $allVMData.PublicIP -port $allVMData.SSHPort -command $command `
			-ignoreLinuxExitCode -runAsSudo

		# Collect the logs generated by shell script
		$null = Collect-TestLogs -LogsDestination $LogDir -ScriptName $shellScriptName `
			-TestType "sh" -PublicIP $allVMData.PublicIP -SSHPort $allVMData.SSHPort `
			-Username $global:user -Password $global:password -TestName $testName

		if ($testState -eq "TestCompleted") {
			$testResult = "PASS"
			Write-LogInfo "Test PASSED"
		} else {
			$testResult = "FAIL"
			Write-LogErr "Test FAILED"
		}
	} catch {
		$ErrorMessage =  $_.Exception.Message
		$ErrorLine = $_.InvocationInfo.ScriptLineNumber
		Write-LogErr "EXCEPTION : $ErrorMessage at line: $ErrorLine"
		$testResult = "FAIL"
	}
	$currentTestResult.TestResult = Get-FinalResultHeader -resultarr $testResult

	return $currentTestResult
}

Main -testParam (ConvertFrom-StringData $TestParams.Replace(";","`n")) `
	-allVMData $AllVmData -currentTestData $CurrentTestData