# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License.

function Main {
    # Create test result
    $currentTestResult = Create-TestResultObject
    $resultArr = @()

    try {
        $noClient = $true
        $noServer = $true
        foreach ($vmData in $allVMData) {
            if ($vmData.RoleName -imatch "client") {
                $clientVMData = $vmData
                $noClient = $false
            }
            elseif ($vmData.RoleName -imatch "server") {
                $noServer = $fase
                $serverVMData = $vmData
            }
        }
        if ($noClient) {
            Throw "No any master VM defined. Be sure that, Client VM role name matches with the pattern `"*master*`". Aborting Test."
        }
        if ($noServer) {
            Throw "No any slave VM defined. Be sure that, Server machine role names matches with pattern `"*slave*`" Aborting Test."
        }
        #region CONFIGURE VM FOR TERASORT TEST
        Write-LogInfo "CLIENT VM details :"
        Write-LogInfo "  RoleName  : $($clientVMData.RoleName)"
        Write-LogInfo "  Public IP : $($clientVMData.PublicIP)"
        Write-LogInfo "  SSH Port  : $($clientVMData.SSHPort)"
        Write-LogInfo "  Location  : $($clientVMData.Location)"
        Write-LogInfo "SERVER VM details :"
        Write-LogInfo "  RoleName  : $($serverVMData.RoleName)"
        Write-LogInfo "  Public IP : $($serverVMData.PublicIP)"
        Write-LogInfo "  SSH Port  : $($serverVMData.SSHPort)"
        Write-LogInfo "  Location  : $($serverVMData.Location)"

        # PROVISION VMS FOR LISA WILL ENABLE ROOT USER AND WILL MAKE ENABLE PASSWORDLESS AUTHENTICATION ACROSS ALL VMS IN SAME HOSTED SERVICE.
        Provision-VMsForLisa -allVMData $allVMData -installPackagesOnRoleNames "none"
        #endregion

        if ($EnableAcceleratedNetworking -or $currentTestData.AdditionalHWConfig.Networking -imatch "SRIOV") {
            $DataPath = "SRIOV"
        } else {
            $DataPath = "Synthetic"
        }
        Write-LogInfo "Getting $DataPath NIC Name."
        $getNicCmd = ". ./utils.sh &> /dev/null && get_active_nic_name"
        $clientNicName = (Run-LinuxCmd -ip $clientVMData.PublicIP -port $clientVMData.SSHPort -username "root" -password $password -command $getNicCmd).Trim()
        $serverNicName = (Run-LinuxCmd -ip $clientVMData.PublicIP -port $serverVMData.SSHPort -username "root" -password $password -command $getNicCmd).Trim()
        Write-LogInfo "CLIENT $DataPath NIC: $clientNicName"
        Write-LogInfo "SERVER $DataPath NIC: $serverNicName"
        if ( $serverNicName -eq $clientNicName) {
            Write-LogInfo "Server and client SRIOV NICs are the same."
        } else {
            Throw "Server and client SRIOV NICs are not same."
        }

        Write-LogInfo "Generating constansts.sh ..."
        $constantsFile = "$LogDir\constants.sh"

        #region Check if VMs share same Public IP
        Set-Content -Value "#Generated by Azure Automation." -Path $constantsFile
        if ($clientVMData.PublicIP -eq $serverVMData.PublicIP) {
            Add-Content -Value "server=$($serverVMData.InternalIP)" -Path $constantsFile
            Add-Content -Value "client=$($clientVMData.InternalIP)" -Path $constantsFile
        } else {
            Add-Content -Value "server=$($serverVMData.PublicIP)" -Path $constantsFile
            Add-Content -Value "client=$($clientVMData.PublicIP)" -Path $constantsFile
        }
        #endregion

        foreach ($param in $currentTestData.TestParameters.param) {
            Add-Content -Value "$param" -Path $constantsFile
            if ($param -imatch "bufferLengths=") {
                $testBuffers= $param.Replace("bufferLengths=(","").Replace(")","").Split(" ")
            }
            if ( $param -imatch "IPversion" ) {
                if ( $param -imatch "IPversion=6" ) {
                    $IPVersion = "IPv6"
                    Add-Content -Value "serverIpv6=$($serverVMData.PublicIPv6)" -Path $constantsFile
                    Add-Content -Value "clientIpv6=$($clientVMData.PublicIPv6)" -Path $constantsFile
                } else {
                    $IPVersion = "IPv4"
                }
            }
        }
        Write-LogInfo "constanst.sh created successfully..."
        Write-LogInfo (Get-Content -Path $constantsFile)
        #endregion

        #region EXECUTE TEST
        $myString = @"
cd /root/
./perf_iperf3.sh &> iperf3tcpConsoleLogs.txt
. utils.sh
collect_VM_properties
"@
        Set-Content "$LogDir\Startiperf3tcpTest.sh" $myString
        Copy-RemoteFiles -uploadTo $clientVMData.PublicIP -port $clientVMData.SSHPort -files "$constantsFile,$LogDir\Startiperf3tcpTest.sh" -username "root" -password $password -upload
        $null = Run-LinuxCmd -ip $clientVMData.PublicIP -port $clientVMData.SSHPort -username "root" -password $password -command "chmod +x *.sh"
        $testJob = Run-LinuxCmd -ip $clientVMData.PublicIP -port $clientVMData.SSHPort -username "root" -password $password -command "/root/Startiperf3tcpTest.sh" -RunInBackground
        #endregion

        #region MONITOR TEST
        while ((Get-Job -Id $testJob).State -eq "Running") {
            $currentStatus = Run-LinuxCmd -ip $clientVMData.PublicIP -port $clientVMData.SSHPort -username "root" -password $password -command "tail -1 iperf3tcpConsoleLogs.txt"
            Write-LogInfo "Current Test Status : $currentStatus"
            Wait-Time -seconds 20
        }

        $finalStatus = Run-LinuxCmd -ip $clientVMData.PublicIP -port $clientVMData.SSHPort -username "root" -password $password -command "cat /root/state.txt"
        Copy-RemoteFiles -downloadFrom $clientVMData.PublicIP -port $clientVMData.SSHPort -username "root" -password $password -download -downloadTo $LogDir -files "/root/iperf3tcpConsoleLogs.txt"
        $iperf3LogDir = "$LogDir\iperf3Data"
        New-Item -itemtype directory -path $iperf3LogDir -Force -ErrorAction SilentlyContinue | Out-Null
        Copy-RemoteFiles -downloadFrom $clientVMData.PublicIP -port $clientVMData.SSHPort -username "root" -password $password -download -downloadTo $iperf3LogDir -files "iperf-client-tcp*"
        Copy-RemoteFiles -downloadFrom $clientVMData.PublicIP -port $clientVMData.SSHPort -username "root" -password $password -download -downloadTo $iperf3LogDir -files "iperf-server-tcp*"
        Copy-RemoteFiles -downloadFrom $clientVMData.PublicIP -port $clientVMData.SSHPort -username "root" -password $password -download -downloadTo $LogDir -files "VM_properties.csv"
        $testSummary = $null
        foreach ($BufferSize_Bytes in $testBuffers) {
            # remove extra warnings
            $serverContent = Get-Content $iperf3LogDir\iperf-server-tcp-IPv4-buffer-$BufferSize_Bytes-conn-1-instance-1.txt
            while(!$serverContent[0].ToString().Contains("{")) {
                $serverContent=$serverContent[1..($serverContent.Length-1)]
            }
            $clientContent = Get-Content $iperf3LogDir\iperf-client-tcp-IPv4-buffer-$BufferSize_Bytes-conn-1-instance-1.txt
            while(!$clientContent[0].ToString().Contains("{")) {
                $clientContent=$clientContent[1..($clientContent.Length-1)]
            }
            $serverJson = ConvertFrom-Json -InputObject ([string]($serverContent))
            $clientJson = ConvertFrom-Json -InputObject ([string]($clientContent))
            $RxThroughput_Gbps = [math]::Round($serverJson.end.sum_received.bits_per_second/1000000000,2)
            $TxThroughput_Gbps = [math]::Round($clientJson.end.sum_received.bits_per_second/1000000000,2)
            $RetransmittedSegments = $clientJson.end.streams.sender.retransmits
            $CongestionWindowSize_KB_Total = 0
            foreach ($interval in $clientJson.intervals) {
                $CongestionWindowSize_KB_Total += $interval.streams.snd_cwnd
            }
            $CongestionWindowSize_KB = [math]::Round($CongestionWindowSize_KB_Total / $clientJson.intervals.Count / 1024 )
            $connResult="ClientTxGbps=$TxThroughput_Gbps"
            $metaData = "Buffer=$BufferSize_Bytes Bytes Connections=1"
            $resultSummary +=  Create-ResultSummary -testResult $connResult -metaData $metaData -checkValues "PASS,FAIL,ABORTED" -testName $currentTestData.testName
        }

        if ($finalStatus -imatch "TestFailed") {
            Write-LogErr "Test failed. Last known status : $currentStatus."
            $testResult = "FAIL"
        }
        elseif ($finalStatus -imatch "TestAborted") {
            Write-LogErr "Test Aborted. Last known status : $currentStatus."
            $testResult = "ABORTED"
        }
        elseif ($finalStatus -imatch "TestCompleted") {
            Write-LogInfo "Test Completed."
            $testResult = "PASS"
        }
        elseif ($finalStatus -imatch "TestRunning") {
            Write-LogInfo "Powershell backgroud job for test is completed but VM is reporting that test is still running. Please check $LogDir\zkConsoleLogs.txt"
            Write-LogInfo "Contests of summary.log : $testSummary"
            $testResult = "PASS"
        }
        Write-LogInfo "Test result : $testResult"
        Write-LogInfo "Test Completed"

        Write-LogInfo "Analyzing the test results.."
        $dataSource = $xmlConfig.config.$TestPlatform.database.server
        $user = $xmlConfig.config.$TestPlatform.database.user
        $password = $xmlConfig.config.$TestPlatform.database.password
        $database = $xmlConfig.config.$TestPlatform.database.dbname
        $dataTableName = $xmlConfig.config.$TestPlatform.database.dbtable
        $TestCaseName = $xmlConfig.config.$TestPlatform.database.testTag
        $TestDate = "$(Get-Date -Format 'yyyy/MM/dd HH:mm:ss')"
        $GuestDistro    = cat "$LogDir\VM_properties.csv" | Select-String "OS type"| %{$_ -replace ",OS type,",""}
        $HostType   = $Platform
        $HostBy = $TestLocation
        $HostOS = cat "$LogDir\VM_properties.csv" | Select-String "Host Version"| %{$_ -replace ",Host Version,",""}
        $GuestOSType    = "Linux"
        $GuestDistro    = cat "$LogDir\VM_properties.csv" | Select-String "OS type"| %{$_ -replace ",OS type,",""}
        $GuestSize = $clientVMData.InstanceSize
        $KernelVersion  = cat "$LogDir\VM_properties.csv" | Select-String "Kernel version"| %{$_ -replace ",Kernel version,",""}
        if ($KernelVersion.Length -ge 28) {
            $KernelVersion = $KernelVersion.Trim().Substring(0,28)
        }
        $ProtocolType = "TCP"

        $connectionString = "Server=$dataSource;uid=$user; pwd=$password;Database=$database;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
        $SQLQuery = "INSERT INTO $dataTableName (TestCaseName,DataPath,TestDate,HostBy,HostOS,HostType,GuestSize,GuestOSType,GuestDistro,KernelVersion,IPVersion,ProtocolType,BufferSize_Bytes,RxThroughput_Gbps,TxThroughput_Gbps,RetransmittedSegments,CongestionWindowSize_KB) VALUES"
        foreach ($BufferSize_Bytes in $testBuffers) {
            # remove extra warnings
            $serverContent = Get-Content $iperf3LogDir\iperf-server-tcp-IPv4-buffer-$BufferSize_Bytes-conn-1-instance-1.txt
            while(!$serverContent[0].ToString().Contains("{")) {
                $serverContent=$serverContent[1..($serverContent.Length-1)]
            }
            $clientContent = Get-Content $iperf3LogDir\iperf-client-tcp-IPv4-buffer-$BufferSize_Bytes-conn-1-instance-1.txt
            while(!$clientContent[0].ToString().Contains("{")) {
                $clientContent=$clientContent[1..($clientContent.Length-1)]
            }
            $serverJson = ConvertFrom-Json -InputObject ([string]($serverContent))
            $clientJson = ConvertFrom-Json -InputObject ([string]($clientContent))
            $RxThroughput_Gbps = [math]::Round($serverJson.end.sum_received.bits_per_second/1000000000,2)
            $TxThroughput_Gbps = [math]::Round($clientJson.end.sum_received.bits_per_second/1000000000,2)
            $RetransmittedSegments = $clientJson.end.streams.sender.retransmits
            $CongestionWindowSize_KB_Total = 0
            foreach ($interval in $clientJson.intervals) {
                $CongestionWindowSize_KB_Total += $interval.streams.snd_cwnd
            }
            $CongestionWindowSize_KB = [math]::Round($CongestionWindowSize_KB_Total / $clientJson.intervals.Count / 1024 )
            $SQLQuery += "('$TestCaseName','$DataPath','$TestDate','$HostBy','$HostOS','$HostType','$GuestSize','$GuestOSType','$GuestDistro','$KernelVersion','$IPVersion','$ProtocolType','$BufferSize_Bytes','$RxThroughput_Gbps','$TxThroughput_Gbps','$RetransmittedSegments','$CongestionWindowSize_KB'),"
            $currentTestResult.TestSummary += Create-ResultSummary -testResult $RxThroughput_Gbps -metaData "Buffer : $BufferSize_Bytes Bytes, Rx ThroughputGbps" -checkValues "PASS,FAIL,ABORTED" -testName $currentTestData.testName
        }
        if ($dataSource -And $user -And $password -And $database -And $dataTableName) {
            Write-LogInfo "Uploading the test results.."
            $SQLQuery = $SQLQuery.TrimEnd(',')
            Write-LogInfo $SQLQuery
            $connection = New-Object System.Data.SqlClient.SqlConnection
            $connection.ConnectionString = $connectionString
            $connection.Open()

            $command = $connection.CreateCommand()
            $command.CommandText = $SQLQuery
            $null = $command.executenonquery()
            $connection.Close()
            Write-LogInfo "Uploading the test results done!!"
        } else {
            Write-LogInfo "Invalid database details. Failed to upload result to database!"
        }
    } catch {
        $line = $_.InvocationInfo.ScriptLineNumber
        $script_name = ($_.InvocationInfo.ScriptName).Replace($PWD,".")
        $ErrorMessage =  $_.Exception.Message
        Write-LogInfo "EXCEPTION : $ErrorMessage"
        Write-LogInfo "Source : Line $line in script $script_name."
    } finally {
        $metaData = "iperf3tcp RESULT"
        if (!$testResult) {
            $testResult = "Aborted"
        }
        $resultArr += $testResult
    }

    $currentTestResult.TestResult = Get-FinalResultHeader -resultarr $resultArr
    return $currentTestResult.TestResult
}

Main
