# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License.
param([object] $AllVmData,
		[object] $CurrentTestData)

function Main {
	# Create test result
	$superUser = "root"
	$testResult = $null

	try {
		# Checking NFF GO DPDK compatibility
		$compatibleDistro = @("UBUNTU")
		if (!(Is-DpdkCompatible -CompatibleDistro $compatibleDistro -DetectedDistro $global:DetectedDistro)) {
			return $global:ResultSkipped
		}

		# PROVISION VMS FOR LISA WILL ENABLE ROOT USER AND WILL MAKE ENABLE PASSWORDLESS AUTHENTICATION ACROSS ALL VMS IN SAME HOSTED SERVICE.
		Provision-VMsForLisa -allVMData $allVMData -installPackagesOnRoleNames "none"
		#endregion

		Write-LogInfo "Generating constants.sh ..."
		$constantsFile = "$LogDir\constants.sh"
		Set-Content -Value "#Generated by Azure Automation." -Path $constantsFile
		Add-Content -Value "vms=$($vmData.RoleName)" -Path $constantsFile
		Add-Content -Value "client=$($vmData.InternalIP)" -Path $constantsFile
		Add-Content -Value "server=$($vmData.InternalIP)" -Path $constantsFile

		foreach ($param in $currentTestData.TestParameters.param) {
			Add-Content -Value "$param" -Path $constantsFile
		}

		Write-LogInfo "constants.sh created successfully..."
		Write-LogInfo (Get-Content -Path $constantsFile)
		#endregion

		#region INSTALL CONFIGURE DPDK
		$install_configure_dpdk = @"
cd /root/
./dpdkSetup.sh > dpdkConsoleLogs.txt 2>&1
. utils.sh
collect_VM_properties
"@
		Set-Content "$LogDir\StartDpdkNffGoSetup.sh" $install_configure_dpdk
		Copy-RemoteFiles -uploadTo $vmData.PublicIP -port $vmData.SSHPort `
			-files "$constantsFile,$LogDir\StartDpdkNffGoSetup.sh" -username $superUser -password $password -upload

		Run-LinuxCmd -ip $vmData.PublicIP -port $vmData.SSHPort `
			-username $superUser -password $password -command "chmod +x *.sh" | Out-Null
		$testJob = Run-LinuxCmd -ip $vmData.PublicIP -port $vmData.SSHPort `
			-username $superUser -password $password -command "./StartDpdkNffGoSetup.sh" -RunInBackground
		#endregion

		#region MONITOR INSTALL CONFIGURE DPDK
		while ((Get-Job -Id $testJob).State -eq "Running") {
			$currentStatus = Run-LinuxCmd -ip $vmData.PublicIP -port $vmData.SSHPort `
				-username $superUser -password $password -command "tail -2 dpdkConsoleLogs.txt | head -1"
			Write-LogInfo "Current Test Status : $currentStatus"
			Wait-Time -seconds 20
		}
		$dpdkStatus = Run-LinuxCmd -ip $vmData.PublicIP -port $vmData.SSHPort `
			-username $superUser -password $password -command "cat /root/state.txt"
		$testResult = Get-TestStatus $dpdkStatus
		if ($testResult -ne "PASS") {
			Copy-RemoteFiles -downloadFrom $vmData.PublicIP -port $vmData.SSHPort `
				-username $superUser -password $password -download -downloadTo $LogDir -files "*.txt, *.log"
			return $testResult
		}

		#region INSTALL CONFIGURE NFF-GO
		$build_test_nff_go = @"
cd /root/
./build_test_nff_go.sh > nffGoConsoleLogs.txt 2>&1
. utils.sh
collect_VM_properties
"@
		Set-Content "$LogDir\StartNffGoSetup.sh" $build_test_nff_go
		Copy-RemoteFiles -uploadTo $vmData.PublicIP -port $vmData.SSHPort `
			-files "$LogDir\StartNffGoSetup.sh" -username $superUser -password $password -upload

		Run-LinuxCmd -ip $vmData.PublicIP -port $vmData.SSHPort `
			-username $superUser -password $password -command "chmod +x *.sh" | Out-Null
		$testJob = Run-LinuxCmd -ip $vmData.PublicIP -port $vmData.SSHPort `
			-username $superUser -password $password -command "./StartNffGoSetup.sh" -RunInBackground
		#endregion

		#region MONITOR INSTALL CONFIGURE NFF-GO
		while ((Get-Job -Id $testJob).State -eq "Running") {
			$currentStatus = Run-LinuxCmd -ip $vmData.PublicIP -port $vmData.SSHPort `
				-username $superUser -password $password -command "tail -2 nffGoConsoleLogs.txt | head -1"
			Write-LogInfo "Current Test Status : $currentStatus"
			Wait-Time -seconds 20
		}
		$ovsStatus = Run-LinuxCmd -ip $vmData.PublicIP -port $vmData.SSHPort `
			-username $superUser -password $password -command "cat /root/state.txt"
		$testResult = Get-TestStatus $ovsStatus

		Copy-RemoteFiles -downloadFrom $vmData.PublicIP -port $vmData.SSHPort `
			-username $superUser -password $password -download -downloadTo $LogDir -files "*.txt, *.log"
	} catch {
		$ErrorMessage =  $_.Exception.Message
		$ErrorLine = $_.InvocationInfo.ScriptLineNumber
		Write-LogErr "EXCEPTION : $ErrorMessage at line: $ErrorLine"
		$testResult = "FAIL"
	}
	return $testResult
}

Main
