from .assertpy import WarningLoggingAdapter as WarningLoggingAdapter
from .assertpy import add_extension as add_extension
from .assertpy import assert_that as assert_that
from .assertpy import assert_warn as assert_warn
from .assertpy import fail as fail
from .assertpy import remove_extension as remove_extension
from .assertpy import soft_assertions as soft_assertions
from .assertpy import soft_fail as soft_fail
from .file import contents_of as contents_of
