from typing import Any

from .assertpy import AssertionBuilder

def contents_of(file: Any, encoding: str = ...) -> str: ...

class FileMixin:
    def exists(self) -> AssertionBuilder: ...
    def does_not_exist(self) -> AssertionBuilder: ...
    def is_file(self) -> AssertionBuilder: ...
    def is_directory(self) -> AssertionBuilder: ...
    def is_named(self, filename: Any) -> AssertionBuilder: ...
    def is_child_of(self, parent: Any) -> AssertionBuilder: ...
