# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

import re
from typing import Any, Dict, List, Set, Tuple

from assertpy import assert_that

from lisa import (
    Logger,
    Node,
    TestCaseMetadata,
    TestSuite,
    TestSuiteMetadata,
    schema,
    search_space,
    simple_requirement,
)
from lisa.features import Disk
from lisa.features.disks import DiskPremiumSSDLRS, DiskStandardSSDLRS
from lisa.operating_system import BSD, Windows
from lisa.sut_orchestrator import AZURE
from lisa.tools import Dmesg, Fdisk, Lsblk
from lisa.tools.lsblk import DiskInfo
from lisa.tools.pvcreate import Pvcreate
from lisa.tools.pvremove import Pvremove
from lisa.util import (
    BadEnvironmentStateException,
    LisaException,
    SkippedException,
    check_till_timeout,
)


@TestSuiteMetadata(
    area="storage",
    category="functional",
    description="""
    Validates that hot-added data disks are usable by the LVM stack.

    PASS/FAIL is determined by functional gates only: hot-add
    enumeration in lsblk, 'fdisk -l' listing, pvcreate on all new
    devices, and a post-pvcreate lsblk check that no device is missing
    or reports size 0. NVMe 'Identify ... failed' messages found in
    dmesg are logged (not asserted) because some guests recover via
    kernel retry and complete the workload anyway.
    """,
    owner="rabdulfaizy",
    maturity="preview",
)
class LvmHotAddSuite(TestSuite):
    _DATA_DISK_SIZE_IN_GB = 10
    _DEFAULT_TIMEOUT = 3600
    # Time budget for polling lsblk after a hot-add: udev and the NVMe
    # rescan can lag behind the hot-add ARM operation by tens of seconds
    # on larger bursts. 60 sec has been enough for D8ds_v6 with 24 disks;
    # bump this if larger VM sizes / disk counts prove flaky.
    _HOT_ADD_LSBLK_POLL_TIMEOUT = 60
    # Poll cadence for the lsblk wait. Small enough that a fast hot-add
    # returns promptly, large enough not to hammer the SUT with SSH
    # invocations while udev is settling.
    _HOT_ADD_LSBLK_POLL_INTERVAL = 2

    # Match any Identify-family failure surfaced by the guest NVMe driver
    # so we can log bad-status returns from the NVMe controller, e.g.:
    #   nvme nvme1: Identify NS List failed (status=0xb)
    _NVME_IDENTIFY_FAIL_REGEX = re.compile(
        r"nvme\s+(?P<ctrl>nvme\d+):\s+Identify[^\n]*?failed\s+"
        r"\(status=(?P<status>0x[0-9a-fA-F]+)\)"
    )
    # NVMe status codes worth calling out separately in the log because
    # they indicate the controller returned an invalid response to a
    # spec-compliant Identify command (NVMe 1.4 sec 4.6.1 / 5.14.1.10):
    #   0xb  - Invalid Namespace or Format
    #   0x2  - Invalid Field in Command
    #   0xa  - Invalid Format
    _NVME_TRACKED_STATUS_CODES: Set[str] = {"0xb", "0x2", "0xa"}

    @TestCaseMetadata(
        description="""
        Hot-adds ALL remaining standard SSD data disks in a single call
        up to the VM's max_data_disk_count, then runs 'fdisk -l' /
        'pvcreate' on all newly attached devices and re-runs lsblk to
        confirm the devices remain usable. Also scans dmesg for NVMe
        'Identify ... failed' messages (informational only; does not
        fail the test).

        Steps:
        1. Snapshot lsblk output.
        2. Hot-add all remaining data disks in one call and verify they
           appear in lsblk with the expected size.
        3. Run 'fdisk -l' and confirm exit code 0.
        4. Run 'pvcreate' on ALL newly attached devices in a single
           bulk command so LVM opens every device in one syscall burst.
        5. Re-run lsblk and confirm each device still reports the
           expected size (did not collapse to 0B).
        6. Scan dmesg for 'nvme nvmeN: Identify ... failed (status=...)'
           and log an info line if any are found. PASS/FAIL is decided
           by steps 1-5 only.

        Parallel mode stresses udev: the burst of NS-Changed AENs after
        a bulk attach can cause pvcreate to open devices before udev has
        finished populating /sys/. The bulk pvcreate call amplifies that
        pressure by opening every device in one syscall.

        This test is generated by the lisa_test_writer prompt.
        """,
        priority=1,
        timeout=_DEFAULT_TIMEOUT,
        requirement=simple_requirement(
            supported_platform_type=[AZURE],
            unsupported_os=[BSD, Windows],
            disk=DiskStandardSSDLRS(
                # Require SKU capability, not a pre-attached disk. Using
                # 'data_disk_count' here forces LISA to attach N placeholder
                # disks at deploy time and burns LUN 0..N-1, so the test can
                # only hot-add max_data_disk_count - N devices (odd counts,
                # smaller burst). 'max_data_disk_count' filters at capability
                # level so ALL LUNs remain free for the hot-add burst.
                max_data_disk_count=search_space.IntRange(min=1),
            ),
        ),
        tags=["ai-generated"],
    )
    def verify_hot_add_disks_pvcreate_parallel_standard_ssd(
        self, node: Node, log: Logger, variables: Dict[str, Any]
    ) -> None:
        self._verify_hot_add_and_pvcreate(
            node=node,
            log=log,
            parallel=True,
            disk_type=schema.DiskType.StandardSSDLRS,
            variables=variables,
        )

    @TestCaseMetadata(
        description="""
        Same as verify_hot_add_disks_pvcreate_parallel_standard_ssd but
        uses premium SSD data disks.

        This test is generated by the lisa_test_writer prompt.
        """,
        priority=1,
        timeout=_DEFAULT_TIMEOUT,
        requirement=simple_requirement(
            supported_platform_type=[AZURE],
            unsupported_os=[BSD, Windows],
            disk=DiskPremiumSSDLRS(
                max_data_disk_count=search_space.IntRange(min=1),
            ),
        ),
        tags=["ai-generated"],
    )
    def verify_hot_add_disks_pvcreate_parallel_premium_ssd(
        self, node: Node, log: Logger, variables: Dict[str, Any]
    ) -> None:
        self._verify_hot_add_and_pvcreate(
            node=node,
            log=log,
            parallel=True,
            disk_type=schema.DiskType.PremiumSSDLRS,
            variables=variables,
        )

    @TestCaseMetadata(
        description="""
        Hot-adds standard SSD data disks one at a time up to the VM's
        max_data_disk_count, then runs 'fdisk -l' and issues a
        per-device 'pvcreate <dev>' on each newly attached device, and
        re-runs lsblk to confirm the devices remain usable. Also scans
        dmesg for NVMe 'Identify ... failed' messages (informational
        only; does not fail the test).

        Serial mode is a baseline: udev has time between each attach
        to fully process NS-Changed events, and per-device pvcreate
        gives precise diagnostics (per-device exit code and stderr)
        on partial failures, so this variant should almost always pass.

        This test is generated by the lisa_test_writer prompt.
        """,
        priority=2,
        timeout=_DEFAULT_TIMEOUT,
        requirement=simple_requirement(
            supported_platform_type=[AZURE],
            unsupported_os=[BSD, Windows],
            disk=DiskStandardSSDLRS(
                max_data_disk_count=search_space.IntRange(min=1),
            ),
        ),
        tags=["ai-generated"],
    )
    def verify_hot_add_disks_pvcreate_serial_standard_ssd(
        self, node: Node, log: Logger, variables: Dict[str, Any]
    ) -> None:
        self._verify_hot_add_and_pvcreate(
            node=node,
            log=log,
            parallel=False,
            disk_type=schema.DiskType.StandardSSDLRS,
            variables=variables,
        )

    @TestCaseMetadata(
        description="""
        Same as verify_hot_add_disks_pvcreate_serial_standard_ssd but
        uses premium SSD data disks.

        This test is generated by the lisa_test_writer prompt.
        """,
        priority=2,
        timeout=_DEFAULT_TIMEOUT,
        requirement=simple_requirement(
            supported_platform_type=[AZURE],
            unsupported_os=[BSD, Windows],
            disk=DiskPremiumSSDLRS(
                max_data_disk_count=search_space.IntRange(min=1),
            ),
        ),
        tags=["ai-generated"],
    )
    def verify_hot_add_disks_pvcreate_serial_premium_ssd(
        self, node: Node, log: Logger, variables: Dict[str, Any]
    ) -> None:
        self._verify_hot_add_and_pvcreate(
            node=node,
            log=log,
            parallel=False,
            disk_type=schema.DiskType.PremiumSSDLRS,
            variables=variables,
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _verify_hot_add_and_pvcreate(
        self,
        node: Node,
        log: Logger,
        parallel: bool,
        disk_type: schema.DiskType,
        variables: Dict[str, Any],
    ) -> None:
        # --- Arrange ---
        max_data_disk_count, current_data_disk_count = self._resolve_disk_counts(node)
        free_luns = list(range(current_data_disk_count, max_data_disk_count))
        if not free_luns:
            raise SkippedException(
                "No free LUNs available for hot-add. "
                "Consider setting max_data_disk_count in the runbook."
            )

        # Initialize tools after the skip check so an early skip does
        # not pay the tool-bootstrap cost (e.g. package installs).
        disk = node.features[Disk]
        lsblk = node.tools[Lsblk]
        fdisk = node.tools[Fdisk]
        pvcreate = node.tools[Pvcreate]
        pvremove = node.tools[Pvremove]
        dmesg = node.tools[Dmesg]

        # Optional runbook cap: '-v max_disks_to_add:N' limits the hot-add
        # burst to the first N free LUNs. Default (0/unset) uses ALL free
        # LUNs up to max_data_disk_count. Use this knob to isolate whether
        # a failure is disk-count-sensitive or to shorten runs on VM sizes
        # with very large max_data_disk_count.
        requested_cap = int(variables.get("max_disks_to_add", 0) or 0)
        if 0 < requested_cap < len(free_luns):
            log.info(
                f"Runbook 'max_disks_to_add={requested_cap}' caps the hot-add "
                f"burst from {len(free_luns)} to {requested_cap} disk(s)."
            )
            free_luns = free_luns[:requested_cap]

        log.info(
            f"disk_type={disk_type}, parallel={parallel}, "
            f"max_data_disk_count={max_data_disk_count}, "
            f"current_data_disk_count={current_data_disk_count}, "
            f"free_luns={free_luns}"
        )

        baseline_disks = lsblk.get_disks(force_run=True)
        baseline_names = {d.name for d in baseline_disks}
        size_in_gb = self._DATA_DISK_SIZE_IN_GB
        disks_added: List[str] = []
        new_device_paths: List[str] = []

        try:
            # --- Baseline: 'fdisk -l' count for before/after delta check ---
            baseline_fdisk = fdisk.run("-l", sudo=True, force_run=True)
            baseline_fdisk.assert_exit_code(
                0,
                f"'fdisk -l' failed before hot-add. stderr: {baseline_fdisk.stderr}",
            )
            baseline_fdisk_count = self._count_fdisk_disks(baseline_fdisk.stdout)

            # --- Act: hot-add ---
            if parallel:
                log.info(f"Hot-adding {len(free_luns)} data disks in parallel")
                disks_added = list(
                    disk.add_data_disk(len(free_luns), disk_type, size_in_gb)
                )
                new_device_paths = self._wait_for_new_devices(
                    lsblk=lsblk,
                    baseline_names=baseline_names,
                    expected_count=len(free_luns),
                    size_in_gb=size_in_gb,
                    log=log,
                )
            else:
                for lun in free_luns:
                    log.info(f"Hot-adding data disk at LUN {lun}")
                    added = disk.add_data_disk(1, disk_type, size_in_gb, lun)
                    disks_added.extend(added)
                    new_device_paths = self._wait_for_new_devices(
                        lsblk=lsblk,
                        baseline_names=baseline_names,
                        expected_count=len(disks_added),
                        size_in_gb=size_in_gb,
                        log=log,
                    )

            log.info(f"Newly attached devices: {new_device_paths}")

            # --- Act: 'fdisk -l' listing ---
            # Verify the kernel can enumerate the new devices by
            # comparing the disk count reported by 'fdisk -l' before
            # and after the hot-add. Delta must equal the number of
            # hot-added devices. Count-based comparison is more
            # robust than per-device substring matching against
            # fdisk output.
            fdisk_result = fdisk.run("-l", sudo=True, force_run=True)
            fdisk_result.assert_exit_code(
                0,
                f"'fdisk -l' failed after hot-add. stderr: {fdisk_result.stderr}",
            )
            after_fdisk_count = self._count_fdisk_disks(fdisk_result.stdout)
            fdisk_delta = after_fdisk_count - baseline_fdisk_count
            expected_delta = len(new_device_paths)
            fdisk_delta_msg = (
                f"'fdisk -l' should show {expected_delta} new disk(s) after "
                f"hot-add (before={baseline_fdisk_count}, "
                f"after={after_fdisk_count})"
            )
            assert_that(fdisk_delta).described_as(fdisk_delta_msg).is_equal_to(
                expected_delta
            )

            # --- Act: pvcreate on new devices ---
            # Parallel mode issues one bulk `pvcreate a b c ...` call so
            # LVM opens every device in a single syscall burst -- this
            # matches the original bug repro and maximises udev/NVMe
            # race pressure. Serial mode issues one `pvcreate <dev>` per
            # device so per-device exit codes and stderr are isolated,
            # which gives precise diagnostics on partial failures.
            # Pvcreate.create_pv() enforces exit code 0; a failure here
            # means LVM could not read that device.
            if parallel:
                log.info(
                    f"Running pvcreate (bulk) on {len(new_device_paths)} "
                    f"devices: {new_device_paths}"
                )
                pvcreate.create_pv(*new_device_paths)
            else:
                log.info(
                    f"Running pvcreate (per-device) on {len(new_device_paths)} "
                    f"devices: {new_device_paths}"
                )
                for device_path in new_device_paths:
                    log.info(f"pvcreate {device_path}")
                    pvcreate.create_pv(device_path)

            # --- Assert: sizes did not collapse to 0 after pvcreate ---
            post_disks: Dict[str, DiskInfo] = {
                d.name: d for d in lsblk.get_disks(force_run=True)
            }
            zero_sized: List[str] = []
            missing: List[str] = []
            for device_path in new_device_paths:
                dev_name = device_path.rsplit("/", 1)[-1]
                disk_info = post_disks.get(dev_name)
                if disk_info is None:
                    missing.append(device_path)
                    continue
                if disk_info.size_in_gb == 0:
                    zero_sized.append(device_path)

            if missing:
                missing_msg = (
                    f"Hot-added device(s) {missing} disappeared from "
                    "lsblk after pvcreate."
                )
                raise LisaException(missing_msg)
            zero_sized_msg = (
                f"Hot-added devices {zero_sized} reported size 0 in "
                "lsblk after pvcreate."
            )
            assert_that(zero_sized).described_as(zero_sized_msg).is_empty()

            # --- Diagnostic: log NVMe Identify failures found in dmesg ---
            # Reported at info level, not asserted. Some guests recover
            # via kernel retry and complete the workload successfully
            # even when these messages appear. Only the functional
            # checks above (hot-add enumeration, fdisk, pvcreate,
            # post-lsblk zero-size / missing-device gates) determine
            # PASS/FAIL.
            self._log_nvme_identify_failures(dmesg, log)

        finally:
            # --- Cleanup ---
            if new_device_paths:
                log.debug(f"Cleanup: running pvremove on {new_device_paths}")
                try:
                    pvremove.remove_pv(*new_device_paths, ignore_errors=True)
                except Exception as ex:  # noqa: BLE001
                    log.debug(f"pvremove cleanup raised: {ex}")
            if disks_added:
                log.debug(f"Cleanup: removing data disks {disks_added}")
                try:
                    disk.remove_data_disk(disks_added)
                except Exception as ex:  # noqa: BLE001
                    # A failed detach can leak Azure managed disks and
                    # leave the environment in an unknown state. Raise
                    # BadEnvironmentStateException so LISA recycles the
                    # environment instead of handing a partially-cleaned
                    # node to the next test.
                    raise BadEnvironmentStateException(
                        f"remove_data_disk cleanup failed for {disks_added}: {ex}"
                    ) from ex

    def _resolve_disk_counts(self, node: Node) -> Tuple[int, int]:
        # Guard the capability shape before we index into it. Use explicit
        # 'raise' rather than bare 'assert' so failures aren't silently
        # dropped under 'python -O' and produce a consistent error.
        disk_capability = node.capability.disk
        if disk_capability is None:
            raise LisaException(
                "node.capability.disk must be set by the platform for this test"
            )
        max_data_disk_count = disk_capability.max_data_disk_count
        current_data_disk_count = disk_capability.data_disk_count
        if not isinstance(max_data_disk_count, int):
            raise LisaException(
                "node.capability.disk.max_data_disk_count must be an int, "
                f"got {type(max_data_disk_count).__name__}: "
                f"{max_data_disk_count!r}"
            )
        if not isinstance(current_data_disk_count, int):
            raise LisaException(
                "node.capability.disk.data_disk_count must be an int, "
                f"got {type(current_data_disk_count).__name__}: "
                f"{current_data_disk_count!r}"
            )
        return max_data_disk_count, current_data_disk_count

    def _wait_for_new_devices(
        self,
        lsblk: Lsblk,
        baseline_names: Set[str],
        expected_count: int,
        size_in_gb: int,
        log: Logger,
    ) -> List[str]:
        # Poll lsblk until the expected number of new block devices appear;
        # udev / nvme rescan can lag behind the hot-add ARM operation.
        state: Dict[str, List[DiskInfo]] = {"added": []}

        def _check() -> bool:
            state["added"] = [
                d
                for d in lsblk.get_disks(force_run=True)
                if d.name not in baseline_names
            ]
            # Exact-match: the follow-on assertion requires exactly
            # expected_count devices, so treat 'more than expected' as
            # 'keep polling' (transient over-report) rather than exiting
            # early on an inconsistent count.
            return len(state["added"]) == expected_count

        check_till_timeout(
            _check,
            timeout_message=(
                f"expected {expected_count} new disk(s) in lsblk after "
                f"hot-add, found {len(state['added'])}: "
                f"{[d.name for d in state['added']]}"
            ),
            timeout=self._HOT_ADD_LSBLK_POLL_TIMEOUT,
            interval=self._HOT_ADD_LSBLK_POLL_INTERVAL,
        )
        added_disks: List[DiskInfo] = state["added"]
        assert_that(added_disks).described_as(
            f"expected {expected_count} hot-added disks in lsblk"
        ).is_length(expected_count)
        for d in added_disks:
            size_msg = f"hot-added device {d.device_name} should be {size_in_gb} GB"
            assert_that(d.size_in_gb).described_as(size_msg).is_equal_to(size_in_gb)
        log.debug(f"Detected new devices: {[d.device_name for d in added_disks]}")
        return [d.device_name for d in added_disks]

    def _log_nvme_identify_failures(self, dmesg: Dmesg, log: Logger) -> None:
        dmesg_out = dmesg.get_output(force_run=True)
        matches = list(self._NVME_IDENTIFY_FAIL_REGEX.finditer(dmesg_out))
        if not matches:
            log.info("No 'nvme <ctrl>: Identify ... failed' messages found in dmesg.")
            return

        tracked: List[str] = []
        other: List[str] = []
        for m in matches:
            line = m.group(0)
            status = m.group("status").lower()
            if status in self._NVME_TRACKED_STATUS_CODES:
                tracked.append(line)
            else:
                other.append(line)

        if other:
            log.info(
                "Non-tracked NVMe Identify failures observed in dmesg "
                f"(count={len(other)}); first: {other[0]}"
            )

        if tracked:
            # Informational only; the functional gates in the caller
            # decide PASS/FAIL. This log line makes the NVMe status
            # queryable in test artifacts.
            log.info(
                "Guest kernel logged NVMe 'Identify ... failed' with a "
                "status code that indicates the controller returned an "
                "invalid response to a spec-compliant Identify command "
                f"(NVMe 1.4 sec 4.6.1 / 5.14.1.10). Offending lines: {tracked}"
            )

    @staticmethod
    def _count_fdisk_disks(fdisk_stdout: str) -> int:
        # Each disk header in 'fdisk -l' starts with 'Disk /dev/'; count
        # those lines to get the total number of block devices fdisk
        # sees. Used for before/after delta validation of hot-add.
        return len(re.findall(r"(?m)^Disk /dev/", fdisk_stdout))
