FROM mcr.microsoft.com/azurelinux/base/python:3

ARG PYTHON_VERSION=3.14.7

WORKDIR /app

RUN tdnf update -y && \
    tdnf install -y \
        bzip2-devel \
        build-essential \
        ca-certificates \
        curl \
        git \
        gcc \
        gdbm-devel \
        gobject-introspection-devel \
        cairo-gobject \
        cairo-devel \
        libffi-devel \
        libuuid-devel \
        libvirt-devel \
        make \
        ncurses-devel \
        openssl-devel \
        pkg-config \
        python3-devel \
        python3-pip \
        python3-virtualenv \
        readline-devel \
        sqlite-devel \
        tar \
        wget \
        xz-devel \
        zlib-devel \
        azure-cli \
        cairo-gobject-devel && \
    tdnf clean all && \
    rm -rf /var/cache/tdnf /tmp/*

RUN wget "https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz" && \
    tar -xzf "Python-${PYTHON_VERSION}.tgz" && \
    cd "Python-${PYTHON_VERSION}" && \
    ./configure --prefix=/usr/local --with-ensurepip=install && \
    make -j "$(nproc)" && \
    make altinstall && \
    ln -sf "/usr/local/bin/python${PYTHON_VERSION%.*}" /usr/local/bin/python3 && \
    ln -sf "/usr/local/bin/pip${PYTHON_VERSION%.*}" /usr/local/bin/pip3 && \
    python3 --version | grep -Fx "Python ${PYTHON_VERSION}" && \
    cd /app && \
    rm -rf "Python-${PYTHON_VERSION}" "Python-${PYTHON_VERSION}.tgz"

RUN wget https://aka.ms/downloadazcopy-v10-linux -O azcopy.tar.gz && \
    tar -xvf azcopy.tar.gz && \
    mv azcopy*/azcopy /usr/local/bin/ && \
    rm -rf azcopy*

ENV LISA_azcopy_path="/usr/local/bin/azcopy"

RUN git clone --depth 1 --branch $(curl --silent "https://api.github.com/repos/microsoft/lisa/releases/latest" \
    | grep '"tag_name":' \
    | sed -E 's/.*"([^"]+)".*/\1/') https://github.com/microsoft/lisa.git /app/lisa

WORKDIR /app/lisa

RUN python3 -m pip install --no-cache-dir --upgrade pip || true && \
    python3 -m pip install --no-cache-dir --editable .[ado,azure,libvirt,baremetal] --config-settings editable_mode=compat
