# config types
CONFIG_CONFIG = "config"
CONFIG_PLATFORM = "platform"
CONFIG_ENVIRONMENT_FACTORY = "environmentFactory"

# path related
PATH_REMOTE_ROOT = "lisa_working"
PATH_TOOL = "tool"
PATH_SCRIPT = "script"


# list types
LIST = "list"
LIST_CASE = "case"

# common
NODE = "node"
NAME = "name"
VALUE = "value"
TYPE = "type"
PATH = "path"
PATHS = "paths"
STRATEGY = "strategy"
FILE = "file"
HTTP = "http"
IS_DEFAULT = "isDefault"
WARN_AS_ERROR = "warnAsError"


# by level
PARENT = "parent"
OPERATION = "operation"
OPERATION_REMOVE = "remove"
OPERATION_ADD = "add"
OPERATION_OVERWRITE = "overwrite"

EXTENSION = "extension"

VARIABLE = "variable"
VARIABLE_ISSECRET = "isSecret"

ARTIFACT = "artifact"
ARTIFACT_TYPE_VHD = "vhd"
ARTIFACT_LOCATIONS = "locations"
ARTIFACT_LOCATIONS_TYPE_HTTP = "http"

ENVIRONMENT = "environment"
ENVIRONMENT_MAX_CONCURRENDCY = "maxConcurrency"
ENVIRONMENTS = "environments"
ENVIRONMENTS_TOPOLOGY = "topology"
ENVIRONMENTS_TEMPLATE = "template"
ENVIRONMENTS_TEMPLATE_NODE_COUNT = "nodeCount"
ENVIRONMENTS_NODES = "nodes"
ENVIRONMENTS_NODES_SPEC = "spec"
ENVIRONMENTS_NODES_REMOTE = "remote"
ENVIRONMENTS_NODES_LOCAL = "local"
ENVIRONMENTS_NODES_REMOTE_ADDRESS = "address"
ENVIRONMENTS_NODES_REMOTE_PORT = "port"
ENVIRONMENTS_NODES_REMOTE_PUBLIC_ADDRESS = "publicAddress"
ENVIRONMENTS_NODES_REMOTE_PUBLIC_PORT = "publicPort"
ENVIRONMENTS_NODES_REMOTE_USERNAME = "username"
ENVIRONMENTS_NODES_REMOTE_PASSWORD = "password"
ENVIRONMENTS_NODES_REMOTE_PRIVATEKEYFILE = "privateKeyFile"

NOTIFIER = "notifier"

PLATFORM = "platform"
PLATFORM_AZURE = "azure"
PLATFORM_READY = "ready"

TESTCASE = "testcase"
TESTCASE_CRITERIA = "criteria"
TESTCASE_CRITERIA_AREA = "area"
TESTCASE_CRITERIA_CATEGORY = "category"
TESTCASE_CRITERIA_PRIORITY = "priority"
TESTCASE_CRITERIA_TAG = "tag"
TESTCASE_FORCEINCLUDE = "forceInclude"
TESTCASE_ITERATION = "iteration"
TESTCASE_IGNOREFAILURE = "ignoreFailure"
TESTCASE_INCLUDE = "include"
TESTCASE_RETRY = "retry"
