from typing import Any, Optional

from .hooks import HookImpl as HookImpl
from .hooks import normalize_hookimpl_opts as normalize_hookimpl_opts

class PluginValidationError(Exception):
    plugin: Any = ...
    def __init__(self, plugin: Any, message: Any) -> None: ...

class DistFacade:
    def __init__(self, dist: Any) -> None: ...
    @property
    def project_name(self) -> Any: ...
    def __getattr__(self, attr: Any, default: Optional[Any] = ...) -> Any: ...
    def __dir__(self) -> Any: ...

class PluginManager:
    project_name: Any = ...
    trace: Any = ...
    hook: Any = ...
    def __init__(self, project_name: Any, implprefix: Optional[Any] = ...) -> None: ...
    def register(self, plugin: Any, name: Optional[Any] = ...) -> Any: ...
    def parse_hookimpl_opts(self, plugin: Any, name: Any) -> Any: ...
    def unregister(
        self, plugin: Optional[Any] = ..., name: Optional[Any] = ...
    ) -> Any: ...
    def set_blocked(self, name: Any) -> None: ...
    def is_blocked(self, name: Any) -> Any: ...
    def add_hookspecs(self, module_or_class: Any) -> None: ...
    def parse_hookspec_opts(self, module_or_class: Any, name: Any) -> Any: ...
    def get_plugins(self) -> Any: ...
    def is_registered(self, plugin: Any) -> Any: ...
    def get_canonical_name(self, plugin: Any) -> Any: ...
    def get_plugin(self, name: Any) -> Any: ...
    def has_plugin(self, name: Any) -> Any: ...
    def get_name(self, plugin: Any) -> Any: ...
    def check_pending(self) -> None: ...
    def load_setuptools_entrypoints(
        self, group: Any, name: Optional[Any] = ...
    ) -> Any: ...
    def list_plugin_distinfo(self) -> Any: ...
    def list_name_plugin(self) -> Any: ...
    def get_hookcallers(self, plugin: Any) -> Any: ...
    def add_hookcall_monitoring(self, before: Any, after: Any) -> Any: ...
    def enable_tracing(self) -> Any: ...
    def subset_hook_caller(self, name: Any, remove_plugins: Any) -> Any: ...
